/** [RBAC] Fixed role set — mirrors backend Role enum. */
export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  CHAIRPERSON = "CHAIRPERSON",
  BOARD_MEMBER = "BOARD_MEMBER",
  PRINCIPAL = "PRINCIPAL",
  DEPUTY_PRINCIPAL_ACADEMICS = "DEPUTY_PRINCIPAL_ACADEMICS",
  DEPUTY_PRINCIPAL_ADMIN = "DEPUTY_PRINCIPAL_ADMIN",
  INSTITUTION_ADMIN = "INSTITUTION_ADMIN",
  HOD = "HOD",
  TRAINER = "TRAINER",
  TRAINEE = "TRAINEE",
}